"""Initial schema: tenants, api_keys, runs

Revision ID: c5404f7a7462
Revises: 
Create Date: 2026-02-13 11:04:21.826904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5404f7a7462'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('key_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.TEXT(), nullable=False),
    sa.Column('key_hash', sa.TEXT(), nullable=False),
    sa.Column('label', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('key_id')
    )
    op.create_index('idx_api_keys_tenant', 'api_keys', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_api_keys_tenant_id'), 'api_keys', ['tenant_id'], unique=False)
    op.create_table('runs',
    sa.Column('run_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.TEXT(), nullable=False),
    sa.Column('pack_type', sa.TEXT(), nullable=False),
    sa.Column('profile_version', sa.TEXT(), nullable=False),
    sa.Column('status', sa.TEXT(), nullable=False),
    sa.Column('money_state', sa.TEXT(), nullable=False),
    sa.Column('idempotency_key', sa.TEXT(), nullable=True),
    sa.Column('payload_hash', sa.TEXT(), nullable=False),
    sa.Column('version', sa.BIGINT(), nullable=False),
    sa.Column('reservation_max_cost_usd_micros', sa.BIGINT(), nullable=False),
    sa.Column('actual_cost_usd_micros', sa.BIGINT(), nullable=True),
    sa.Column('minimum_fee_usd_micros', sa.BIGINT(), nullable=False),
    sa.Column('result_bucket', sa.TEXT(), nullable=True),
    sa.Column('result_key', sa.TEXT(), nullable=True),
    sa.Column('result_sha256', sa.TEXT(), nullable=True),
    sa.Column('retention_until', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('lease_token', sa.TEXT(), nullable=True),
    sa.Column('lease_expires_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('finalize_token', sa.TEXT(), nullable=True),
    sa.Column('finalize_stage', sa.TEXT(), nullable=True),
    sa.Column('finalize_claimed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_error_reason_code', sa.TEXT(), nullable=True),
    sa.Column('last_error_detail', sa.TEXT(), nullable=True),
    sa.Column('trace_id', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index('idx_runs_idem', 'runs', ['tenant_id', 'idempotency_key'], unique=False)
    op.create_index('idx_runs_status_lease', 'runs', ['status', 'lease_expires_at'], unique=False)
    op.create_index('idx_runs_tenant_created', 'runs', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_runs_tenant_id'), 'runs', ['tenant_id'], unique=False)
    op.create_table('tenants',
    sa.Column('tenant_id', sa.TEXT(), nullable=False),
    sa.Column('display_name', sa.TEXT(), nullable=False),
    sa.Column('status', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenants')
    op.drop_index(op.f('ix_runs_tenant_id'), table_name='runs')
    op.drop_index('idx_runs_tenant_created', table_name='runs')
    op.drop_index('idx_runs_status_lease', table_name='runs')
    op.drop_index('idx_runs_idem', table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_api_keys_tenant_id'), table_name='api_keys')
    op.drop_index('idx_api_keys_tenant', table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
