"""Add Plan, TenantPlan, TenantUsageDaily for API monetization

Revision ID: f99a7078ce99
Revises: b2f3f5f34551
Create Date: 2026-02-13 13:46:02.242271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f99a7078ce99'
down_revision = 'b2f3f5f34551'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('plan_id', sa.TEXT(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('status', sa.TEXT(), nullable=False),
    sa.Column('default_profile_version', sa.TEXT(), nullable=False),
    sa.Column('features_json', sa.JSON(), nullable=False),
    sa.Column('limits_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_table('tenant_plans',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.TEXT(), nullable=False),
    sa.Column('plan_id', sa.TEXT(), nullable=False),
    sa.Column('status', sa.TEXT(), nullable=False),
    sa.Column('effective_from', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('effective_to', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('changed_by', sa.TEXT(), nullable=True),
    sa.Column('change_reason', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tenant_plans_effective', 'tenant_plans', ['tenant_id', 'effective_from', 'effective_to'], unique=False)
    op.create_index('idx_tenant_plans_tenant_status', 'tenant_plans', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_tenant_plans_tenant_id'), 'tenant_plans', ['tenant_id'], unique=False)
    op.create_table('tenant_usage_daily',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.TEXT(), nullable=False),
    sa.Column('usage_date', sa.DATE(), nullable=False),
    sa.Column('runs_count', sa.BIGINT(), nullable=False),
    sa.Column('success_count', sa.BIGINT(), nullable=False),
    sa.Column('fail_count', sa.BIGINT(), nullable=False),
    sa.Column('cost_usd_micros_sum', sa.BIGINT(), nullable=False),
    sa.Column('reserved_usd_micros_sum', sa.BIGINT(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tenant_usage_daily_tenant_date', 'tenant_usage_daily', ['tenant_id', 'usage_date'], unique=True)
    op.create_index(op.f('ix_tenant_usage_daily_tenant_id'), 'tenant_usage_daily', ['tenant_id'], unique=False)
    op.drop_constraint(op.f('uq_runs_tenant_idempotency'), 'runs', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_runs_tenant_idempotency'), 'runs', ['tenant_id', 'idempotency_key'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_tenant_usage_daily_tenant_id'), table_name='tenant_usage_daily')
    op.drop_index('idx_tenant_usage_daily_tenant_date', table_name='tenant_usage_daily')
    op.drop_table('tenant_usage_daily')
    op.drop_index(op.f('ix_tenant_plans_tenant_id'), table_name='tenant_plans')
    op.drop_index('idx_tenant_plans_tenant_status', table_name='tenant_plans')
    op.drop_index('idx_tenant_plans_effective', table_name='tenant_plans')
    op.drop_table('tenant_plans')
    op.drop_table('plans')
    # ### end Alembic commands ###
